### PR TITLE
Support multiple target architectures including arm64

### PR DESCRIPTION
**Pull request by salekseev**
Closes https://github.com/helaili/github-oidc-auth-app/issues/19

### CODE REVIEW

**Comment by salekseev** [comment]
@helaili any idea what failed exactly on deployment so I can fix it? Thanks.

**Comment by salekseev** [comment]
> The deployment error was a problem on my side, but now there seems to be [some error](https://github.com/helaili/github-oidc-auth-app/actions/runs/5658880475/job/15331230521?pr=18) during the docker build process.

Ah I see, I will try to look into this build error that seems to have to do with cross-compilation for amr64.

**Comment by salekseev** [comment]
@helaili I have corrected a couple of mistakes in the build workflow as well as in the `Dockerfile` itself. Deployment phase is now producing an error as I do not have secrets for it I believe. I have intermixed a bump for `docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1`, let me know if you'd rather this was a separate PR.

**Comment by salekseev** [comment]
I think https://github.com/helaili/github-oidc-auth-app/actions/runs/5661164625/job/15338620256?pr=18#step:7:4 uses `main` tag to deploy to stage but this PR did not push to GCR...

**Comment by helaili** [comment]
Thanks for your patience @salekseev. My PR deployment process was halfway baked.

**Pull request merged**
